# Generated by Django 3.1.1 on 2020-12-17 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_customer'),
        ('shop', '0003_created'),
    ]

    operations = [
    ]
