# Generated by Django 3.1.1 on 2021-04-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_merge_20201216_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Created',
        ),
    ]
