# Generated by Django 3.1.1 on 2021-05-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='note',
        ),
    ]
